
# Copyright 2009 Rudolph Technologies, Inc. All Rights Reserved.
# This software is provided under license and may only be used in
# accordance with the terms of the respective license agreements
# of the owners of the same software, which include, but are not
# limited to, Rudolph Technologies, Inc. Where applicable, refer
# to on-line license agreements provided with the software.

#! /bin/sh
# the next line restarts using wish \
exec wish "$0" "$@"

# interface generated by SpecTcl version 1.1 from /home/hcamp/code/mtc/ashl/astk/aim.ui
#   root     is the parent window for this user interface

proc aim_ui {root args} {

	# this treats "." as a special case

	if {$root == "."} {
	    set base ""
	} else {
	    set base $root
	}
    
	frame $base.usericons1

	frame $base.usericons2

	frame $base.menubar \
		-background #2985b6 \
		-borderwidth 2

	menubutton $base.file \
		-activebackground blue \
		-activeforeground yellow \
		-background #2985b6 \
		-borderwidth 1 \
		-foreground yellow \
		-menu "$base.file.menu" \
		-text File

	menubutton $base.edit \
		-activebackground blue \
		-activeforeground yellow \
		-background #2985b6 \
		-borderwidth 1 \
		-foreground yellow \
		-menu "$base.edit.menu" \
		-text Edit

	menubutton $base.os \
		-activebackground blue \
		-activeforeground yellow \
		-background #2985b6 \
		-borderwidth 1 \
		-foreground yellow \
		-menu "$base.os.menu" \
		-text O.S.

	menubutton $base.srv \
		-activebackground blue \
		-activeforeground yellow \
		-background #2985b6 \
		-borderwidth 1 \
		-foreground yellow \
		-menu "$base.srv.menu" \
		-text Srv
		
	label $base.label#0 \
		-background #2985b6 \
		-foreground white \
		-text "Show:"
		
	entry $base.entry#0 \
		-cursor {} \
		-textvariable add_filter
	bind $base.entry#0 <Key-Return> "refresh_serverlist"

	menubutton $base.help \
		-activebackground blue \
		-activeforeground yellow \
		-background #2985b6 \
		-borderwidth 1 \
		-foreground yellow \
		-menu "$base.help.menu" \
		-text Help

	label $base.label#1 \
		-background #2985b6 \
		-image asjackt \
		-text label

	listbox $base.serverlist \
		-takefocus 1 \
		-yscrollcommand "$base.scrollbar#1 set"

	scrollbar $base.scrollbar#1 \
		-command "$base.serverlist yview" \
		-orient v

	label $base.acname \
		-background #2985b6 \
		-borderwidth 0 \
		-foreground white \
		-text label

	button $base.refreshbutton \
		-activebackground blue \
		-activeforeground yellow \
		-background #2985b6 \
		-command refresh_serverlist \
		-foreground yellow \
		-padx 4 \
		-pady 2 \
		-text Refresh

	button $base.session \
		-activebackground blue \
		-activeforeground yellow \
		-background #2985b6 \
		-command start_session \
		-foreground yellow \
		-padx 4 \
		-pady 2 \
		-text Talk

	label $base.cwd \
		-anchor e \
		-justify left \
		-textvariable aim_cwd \
		-width 20
	catch {
		$base.cwd configure \
			-font -*-Courier-Medium-R-Normal-*-*-120-*-*-*-*-*-*
	}

	button $base.button#3 \
		-command aim_changecwd \
		-highlightthickness 2 \
		-padx 4 \
		-text CWD


	# Geometry management

	grid $base.usericons1 -in $root	-row 5 -column 2  \
		-sticky s
	grid $base.usericons2 -in $root	-row 5 -column 3  \
		-sticky s
	grid $base.menubar -in $root	-row 2 -column 2  \
		-columnspan 8 \
		-sticky ew
	grid $base.file -in $base.menubar	-row 1 -column 1 
	grid $base.edit -in $base.menubar	-row 1 -column 2 
	grid $base.os -in $base.menubar	-row 1 -column 3 
	grid $base.srv -in $base.menubar	-row 1 -column 4 
	grid $base.label#0 -in $base.menubar -row 1 -column 5
	grid $base.entry#0 -in $base.menubar -row 1 -column 6 \
		-sticky ew
	grid $base.help -in $base.menubar	-row 1 -column 7  \
		-sticky e
	grid $base.label#1 -in $root	-row 3 -column 2  \
		-columnspan 2 \
		-sticky n
	grid $base.serverlist -in $root	-row 3 -column 5  \
		-columnspan 4 \
		-rowspan 5 \
		-sticky nesw
	grid $base.scrollbar#1 -in $root	-row 3 -column 9  \
		-rowspan 5 \
		-sticky ns
	grid $base.acname -in $root	-row 4 -column 2  \
		-columnspan 2
	grid $base.refreshbutton -in $root	-row 6 -column 2  \
		-columnspan 2 \
		-pady 4 \
		-sticky nesw
	grid $base.session -in $root	-row 7 -column 2  \
		-columnspan 2 \
		-sticky nesw
	grid $base.cwd -in $root	-row 8 -column 2  \
		-columnspan 6 \
		-sticky ew
	grid $base.button#3 -in $root	-row 8 -column 8  \
		-columnspan 2

	# Resize behavior management

	grid rowconfigure $root 1 -weight 0 -minsize 3
	grid rowconfigure $root 2 -weight 0 -minsize 34
	grid rowconfigure $root 3 -weight 1 -minsize 48
	grid rowconfigure $root 4 -weight 0 -minsize 30
	grid rowconfigure $root 5 -weight 0 -minsize 15
	grid rowconfigure $root 6 -weight 0 -minsize 2
	grid rowconfigure $root 7 -weight 0 -minsize 15
	grid rowconfigure $root 8 -weight 0 -minsize 6
	grid rowconfigure $root 9 -weight 0 -minsize 4
	grid columnconfigure $root 1 -weight 0 -minsize 4
	grid columnconfigure $root 2 -weight 0 -minsize 2
	grid columnconfigure $root 3 -weight 0 -minsize 2
	grid columnconfigure $root 4 -weight 0 -minsize 3
	grid columnconfigure $root 5 -weight 0 -minsize 2
	grid columnconfigure $root 6 -weight 0 -minsize 15
	grid columnconfigure $root 7 -weight 1 -minsize 2
	grid columnconfigure $root 8 -weight 0 -minsize 30
	grid columnconfigure $root 9 -weight 0 -minsize 2
	grid columnconfigure $root 10 -weight 0 -minsize 4

	grid rowconfigure $base.menubar 1 -weight 0 -minsize 15
	grid columnconfigure $base.menubar 1 -weight 0 -minsize 15
	grid columnconfigure $base.menubar 2 -weight 0 -minsize 15
	grid columnconfigure $base.menubar 3 -weight 0 -minsize 15
	grid columnconfigure $base.menubar 4 -weight 0 -minsize 15
	grid columnconfigure $base.menubar 5 -weight 0 -minsize 20
	grid columnconfigure $base.menubar 6 -weight 1 -minsize 15
	grid columnconfigure $base.menubar 7 -weight 0 -minsize 15
# additional interface code

global aim_options
if {[info exists aim_options(geometry)]} {
    wm geometry $root $aim_options(geometry)
} else {
    wm geometry $root +25+25
}

global env; source $env(ASTK_DIR)/aim.code.tcl


# end additional interface code

}


# Allow interface to be run "stand-alone" for testing

catch {
    if [info exists embed_args] {
	# we are running in the plugin
	aim_ui .
    } else {
	# we are running in stand-alone mode
	if {$argv0 == [info script]} {
	    wm title . "Testing aim_ui"
	    aim_ui .
	}
    }
}
