
# Copyright 2009 Rudolph Technologies, Inc. All Rights Reserved.
# This software is provided under license and may only be used in
# accordance with the terms of the respective license agreements
# of the owners of the same software, which include, but are not
# limited to, Rudolph Technologies, Inc. Where applicable, refer
# to on-line license agreements provided with the software.

#! /bin/sh
# the next line restarts using wish \
exec wish "$0" "$@"

# interface generated by SpecTcl version 1.1 from /home/hcamp/code/mtc/ashl/astk/cmdlist.ui
#   root     is the parent window for this user interface

proc cmdlist_ui {root args} {

	# this treats "." as a special case

	if {$root == "."} {
	    set base ""
	} else {
	    set base $root
	}
    
	listbox $base.cmdlist \
		-height 12 \
		-yscrollcommand "$base.scrollbar#1 set"

	scrollbar $base.scrollbar#1 \
		-command "$base.cmdlist yview" \
		-orient v

	scale $base.scale#1 \
		-from 1.0 \
		-label {Cmds Shown} \
		-orient h \
		-relief ridge \
		-showvalue 0 \
		-tickinterval 1.0 \
		-to 3.0 \
		-variable "sessions($root,cmdlevel)"

	button $base.button#4 \
		-command "command_help $base.button#4" \
		-text Help
	catch {
		$base.button#4 configure \
			-font -*-Helvetica-Bold-R-Normal-*-*-120-*-*-*-*-*-*
	}

	button $base.send \
		-command "send_command $base.send $base" \
		-text {Send . . .}

	button $base.button#1 \
		-command "cancel_cmdlist $base.button#1 $base" \
		-text Cancel


	# Geometry management

	grid $base.cmdlist -in $root	-row 1 -column 1  \
		-columnspan 3 \
		-sticky nesw
	grid $base.scrollbar#1 -in $root	-row 1 -column 4  \
		-sticky ns
	grid $base.scale#1 -in $root	-row 2 -column 1  \
		-rowspan 2 \
		-sticky ew
	grid $base.button#4 -in $root	-row 2 -column 2 
	grid $base.send -in $root	-row 3 -column 2 
	grid $base.button#1 -in $root	-row 3 -column 3  \
		-columnspan 2

	# Resize behavior management

	grid rowconfigure $root 1 -weight 1 -minsize 15
	grid rowconfigure $root 2 -weight 0 -minsize 15
	grid rowconfigure $root 3 -weight 0 -minsize 15
	grid columnconfigure $root 1 -weight 1 -minsize 15
	grid columnconfigure $root 2 -weight 0 -minsize 15
	grid columnconfigure $root 3 -weight 0 -minsize 33
	grid columnconfigure $root 4 -weight 0 -minsize 2
# additional interface code
global env; source $env(ASTK_DIR)/cmdlist.code.tcl

# end additional interface code

}


# Allow interface to be run "stand-alone" for testing

catch {
    if [info exists embed_args] {
	# we are running in the plugin
	cmdlist_ui .
    } else {
	# we are running in stand-alone mode
	if {$argv0 == [info script]} {
	    wm title . "Testing cmdlist_ui"
	    cmdlist_ui .
	}
    }
}
