
# Copyright 2009 Rudolph Technologies, Inc. All Rights Reserved.
# This software is provided under license and may only be used in
# accordance with the terms of the respective license agreements
# of the owners of the same software, which include, but are not
# limited to, Rudolph Technologies, Inc. Where applicable, refer
# to on-line license agreements provided with the software.

#! /bin/sh
# the next line restarts using wish \
exec wish "$0" "$@"

# interface generated by SpecTcl version 1.1 from /home/hcamp/code/mtc/ashl/astk/sendmsg.ui
#   root     is the parent window for this user interface

proc sendmsg_ui {root args} {

	# this treats "." as a special case

	if {$root == "."} {
	    set base ""
	} else {
	    set base $root
	}
    
	label $base.label#1 \
		-text {Destination email address:}

	entry $base.entry#1 \
		-cursor {} \
		-textvariable aim_sendmsg(emaildest) \
		-width 40

	label $base.label#4 \
		-text {Your Name:}

	entry $base.entry#2 \
		-cursor {} \
		-textvariable aim_sendmsg(sendername) \
		-width 40

	label $base.label#2 \
		-text {message text:}

	text $base.messagetext \
		-height 8 \
		-width 65 \
		-yscrollcommand "$base.scrollbar#1 set"

	scrollbar $base.scrollbar#1 \
		-command "$base.messagetext yview" \
		-orient v

	label $base.label#3 \
		-text {sample code or data:}

	text $base.codedata \
		-height 4 \
		-width 65 \
		-yscrollcommand "$base.scrollbar#2 set"

	scrollbar $base.scrollbar#2 \
		-command "$base.codedata yview" \
		-orient v

	button $base.button#1 \
		-command "mail_message $root file" \
		-text {Save to File...}

	button $base.button#3 \
		-command "mail_message $root send" \
		-text Send

	button $base.button#2 \
		-command "destroy $root" \
		-text Cancel


	# Geometry management

	grid $base.label#1 -in $root	-row 1 -column 1  \
		-sticky e
	grid $base.entry#1 -in $root	-row 1 -column 2  \
		-columnspan 2 \
		-sticky w
	grid $base.label#4 -in $root	-row 2 -column 1  \
		-sticky ne
	grid $base.entry#2 -in $root	-row 2 -column 2  \
		-columnspan 2 \
		-sticky w
	grid $base.label#2 -in $root	-row 3 -column 1  \
		-sticky ne
	grid $base.messagetext -in $root	-row 3 -column 2  \
		-columnspan 2 \
		-sticky nesw
	grid $base.scrollbar#1 -in $root	-row 3 -column 4  \
		-sticky ns
	grid $base.label#3 -in $root	-row 4 -column 1  \
		-sticky ne
	grid $base.codedata -in $root	-row 4 -column 2  \
		-columnspan 2 \
		-sticky nesw
	grid $base.scrollbar#2 -in $root	-row 4 -column 4  \
		-sticky ns
	grid $base.button#1 -in $root	-row 5 -column 1 
	grid $base.button#3 -in $root	-row 5 -column 2 
	grid $base.button#2 -in $root	-row 5 -column 3 

	# Resize behavior management

	grid rowconfigure $root 1 -weight 0 -minsize 15
	grid rowconfigure $root 2 -weight 0 -minsize 15
	grid rowconfigure $root 3 -weight 1 -minsize 15
	grid rowconfigure $root 4 -weight 1 -minsize 15
	grid rowconfigure $root 5 -weight 0 -minsize 15
	grid columnconfigure $root 1 -weight 0 -minsize 15
	grid columnconfigure $root 2 -weight 0 -minsize 15
	grid columnconfigure $root 3 -weight 0 -minsize 15
	grid columnconfigure $root 4 -weight 0 -minsize 15
# additional interface code
# end additional interface code

}


# Allow interface to be run "stand-alone" for testing

catch {
    if [info exists embed_args] {
	# we are running in the plugin
	sendmsg_ui .
    } else {
	# we are running in stand-alone mode
	if {$argv0 == [info script]} {
	    wm title . "Testing sendmsg_ui"
	    sendmsg_ui .
	}
    }
}
