//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace Common
{
    using System.Xml.Serialization; 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class SystemConfig 
    {

        private string emailServerField;

        private byte emailPortField;

        private SystemConfigCamstarConfig camstarConfigField;

        /// <remarks/>
        public string EmailServer
        {
            get
            {
                return this.emailServerField;
            }
            set
            {
                this.emailServerField = value;
            }
        }

        /// <remarks/>
        public byte EmailPort
        {
            get
            {
                return this.emailPortField;
            }
            set
            {
                this.emailPortField = value;
            }
        }

        /// <remarks/>
        public SystemConfigCamstarConfig CamstarConfig
        {
            get
            {
                return this.camstarConfigField;
            }
            set
            {
                this.camstarConfigField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SystemConfigCamstarConfig
    {

        private string dBServerNameField;

        private string databaseNameField;

        private string dBUserNameField;

        private string dBPasswordEncryptField;

        private string insiteHostField;

        private ushort insitePortField;

        private string insiteUserField;

        private string insitePwdField;

        private string strLogPathField;

        private string stLogrFilePrefixField;

        /// <remarks/>
        public string DBServerName
        {
            get
            {
                return this.dBServerNameField;
            }
            set
            {
                this.dBServerNameField = value;
            }
        }

        /// <remarks/>
        public string DatabaseName
        {
            get
            {
                return this.databaseNameField;
            }
            set
            {
                this.databaseNameField = value;
            }
        }

        /// <remarks/>
        public string DBUserName
        {
            get
            {
                return this.dBUserNameField;
            }
            set
            {
                this.dBUserNameField = value;
            }
        }

        /// <remarks/>
        public string DBPasswordEncrypt
        {
            get
            {
                return this.dBPasswordEncryptField;
            }
            set
            {
                this.dBPasswordEncryptField = value;
            }
        }

        /// <remarks/>
        public string InsiteHost
        {
            get
            {
                return this.insiteHostField;
            }
            set
            {
                this.insiteHostField = value;
            }
        }

        /// <remarks/>
        public ushort InsitePort
        {
            get
            {
                return this.insitePortField;
            }
            set
            {
                this.insitePortField = value;
            }
        }

        /// <remarks/>
        public string InsiteUser
        {
            get
            {
                return this.insiteUserField;
            }
            set
            {
                this.insiteUserField = value;
            }
        }

        /// <remarks/>
        public string InsitePwd
        {
            get
            {
                return this.insitePwdField;
            }
            set
            {
                this.insitePwdField = value;
            }
        }

        /// <remarks/>
        public string strLogPath
        {
            get
            {
                return this.strLogPathField;
            }
            set
            {
                this.strLogPathField = value;
            }
        }

        /// <remarks/>
        public string stLogrFilePrefix
        {
            get
            {
                return this.stLogrFilePrefixField;
            }
            set
            {
                this.stLogrFilePrefixField = value;
            }
        }
    }
}
