//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace Common
{
    using System.Xml.Serialization;

      
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://rudolphtech.com/ToolConfigXMLSchema.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://rudolphtech.com/ToolConfigXMLSchema.xsd", IsNullable = false)]
    public partial class ToolConfig
    {

        private string toolTypeField;

        private string toolidField;

        private int numberOfPortsField;

        private bool timeoutBeforeStartFlagField;

        private int timeoutBeforeStartSecondsField;

        private bool enableAllEventsField;

        private bool enableAllAlarmsField;

        private bool enableDefinedEventsAtAppStartField;

        private bool defineEventsAtAppStartField;

        private int controlStateSVIDField;

        private int processStateSVIDField;

        private bool emailOnAlarmsFlagField;

        private string[] emailAddresseesForAlarmsField;

        private bool emailOnAppShutdownFlagField;

        private string[] emailAddresseesForAppshutdownField;

        private string traceLogFilesPathField;

        private string logFilesPathField;

        private ToolConfigField[] operatorWaferTableFieldsField;

        private ToolConfigField1[] engineerWaferTableFieldsField;

        private ToolConfigEqConst[] eqConstValListField;

        private ToolConfigEqConst1[] eqConstListField;

        private ToolConfigSvid[] sVidListField;

        private ToolConfigSvid1[] alarmListField;

        private ToolConfigReport[] traceReportsField;

        private ToolConfigReport2[] eventReportsField;

        /// <remarks/>
        public string ToolType
        {
            get
            {
                return this.toolTypeField;
            }
            set
            {
                this.toolTypeField = value;
            }
        }

        /// <remarks/>
        public string Toolid
        {
            get
            {
                return this.toolidField;
            }
            set
            {
                this.toolidField = value;
            }
        }

        /// <remarks/>
        public int NumberOfPorts
        {
            get
            {
                return this.numberOfPortsField;
            }
            set
            {
                this.numberOfPortsField = value;
            }
        }

        /// <remarks/>
        public bool TimeoutBeforeStartFlag
        {
            get
            {
                return this.timeoutBeforeStartFlagField;
            }
            set
            {
                this.timeoutBeforeStartFlagField = value;
            }
        }

        /// <remarks/>
        public int TimeoutBeforeStartSeconds
        {
            get
            {
                return this.timeoutBeforeStartSecondsField;
            }
            set
            {
                this.timeoutBeforeStartSecondsField = value;
            }
        }

        /// <remarks/>
        public bool EnableAllEvents
        {
            get
            {
                return this.enableAllEventsField;
            }
            set
            {
                this.enableAllEventsField = value;
            }
        }

        /// <remarks/>
        public bool EnableAllAlarms
        {
            get
            {
                return this.enableAllAlarmsField;
            }
            set
            {
                this.enableAllAlarmsField = value;
            }
        }

        /// <remarks/>
        public bool EnableDefinedEventsAtAppStart
        {
            get
            {
                return this.enableDefinedEventsAtAppStartField;
            }
            set
            {
                this.enableDefinedEventsAtAppStartField = value;
            }
        }

        /// <remarks/>
        public bool DefineEventsAtAppStart
        {
            get
            {
                return this.defineEventsAtAppStartField;
            }
            set
            {
                this.defineEventsAtAppStartField = value;
            }
        }

        /// <remarks/>
        public int ControlStateSVID
        {
            get
            {
                return this.controlStateSVIDField;
            }
            set
            {
                this.controlStateSVIDField = value;
            }
        }

        /// <remarks/>
        public int ProcessStateSVID
        {
            get
            {
                return this.processStateSVIDField;
            }
            set
            {
                this.processStateSVIDField = value;
            }
        }

        /// <remarks/>
        public bool EmailOnAlarmsFlag
        {
            get
            {
                return this.emailOnAlarmsFlagField;
            }
            set
            {
                this.emailOnAlarmsFlagField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Addressee", IsNullable = false)]
        public string[] EmailAddresseesForAlarms
        {
            get
            {
                return this.emailAddresseesForAlarmsField;
            }
            set
            {
                this.emailAddresseesForAlarmsField = value;
            }
        }

        /// <remarks/>
        public bool EmailOnAppShutdownFlag
        {
            get
            {
                return this.emailOnAppShutdownFlagField;
            }
            set
            {
                this.emailOnAppShutdownFlagField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Addressee", IsNullable = false)]
        public string[] EmailAddresseesForAppshutdown
        {
            get
            {
                return this.emailAddresseesForAppshutdownField;
            }
            set
            {
                this.emailAddresseesForAppshutdownField = value;
            }
        }

        /// <remarks/>
        public string TraceLogFilesPath
        {
            get
            {
                return this.traceLogFilesPathField;
            }
            set
            {
                this.traceLogFilesPathField = value;
            }
        }

        /// <remarks/>
        public string LogFilesPath
        {
            get
            {
                return this.logFilesPathField;
            }
            set
            {
                this.logFilesPathField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Field", IsNullable = false)]
        public ToolConfigField[] OperatorWaferTableFields
        {
            get
            {
                return this.operatorWaferTableFieldsField;
            }
            set
            {
                this.operatorWaferTableFieldsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Field", IsNullable = false)]
        public ToolConfigField1[] EngineerWaferTableFields
        {
            get
            {
                return this.engineerWaferTableFieldsField;
            }
            set
            {
                this.engineerWaferTableFieldsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("EqConst", IsNullable = false)]
        public ToolConfigEqConst[] EqConstValList
        {
            get
            {
                return this.eqConstValListField;
            }
            set
            {
                this.eqConstValListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("EqConst", IsNullable = false)]
        public ToolConfigEqConst1[] EqConstList
        {
            get
            {
                return this.eqConstListField;
            }
            set
            {
                this.eqConstListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Svid", IsNullable = false)]
        public ToolConfigSvid[] SVidList
        {
            get
            {
                return this.sVidListField;
            }
            set
            {
                this.sVidListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Svid", IsNullable = false)]
        public ToolConfigSvid1[] AlarmList
        {
            get
            {
                return this.alarmListField;
            }
            set
            {
                this.alarmListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Report", IsNullable = false)]
        public ToolConfigReport[] TraceReports
        {
            get
            {
                return this.traceReportsField;
            }
            set
            {
                this.traceReportsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("report", IsNullable = false)]
        public ToolConfigReport2[] eventReports
        {
            get
            {
                return this.eventReportsField;
            }
            set
            {
                this.eventReportsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://rudolphtech.com/ToolConfigXMLSchema.xsd")]
    public partial class ToolConfigField
    {
   
        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://rudolphtech.com/ToolConfigXMLSchema.xsd")]
    public partial class ToolConfigField1
    {

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://rudolphtech.com/ToolConfigXMLSchema.xsd")]
    public partial class ToolConfigEqConst
    {

        private ushort valField;

        private bool valFieldSpecified;

        private string nameField;

        /// <remarks/>
        public ushort val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valSpecified
        {
            get
            {
                return this.valFieldSpecified;
            }
            set
            {
                this.valFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://rudolphtech.com/ToolConfigXMLSchema.xsd")]
    public partial class ToolConfigEqConst1
    {

        private ushort valField;

        private bool valFieldSpecified;

        private string nameField;

        /// <remarks/>
        public ushort val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valSpecified
        {
            get
            {
                return this.valFieldSpecified;
            }
            set
            {
                this.valFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://rudolphtech.com/ToolConfigXMLSchema.xsd")]
    public partial class ToolConfigSvid
    {

        private object[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("id", typeof(uint))]
        [System.Xml.Serialization.XmlElementAttribute("name", typeof(string))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://rudolphtech.com/ToolConfigXMLSchema.xsd")]
    public partial class ToolConfigSvid1
    {

        private object[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("id", typeof(uint))]
        [System.Xml.Serialization.XmlElementAttribute("name", typeof(string))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://rudolphtech.com/ToolConfigXMLSchema.xsd")]
    public partial class ToolConfigReport
    {

        private ToolConfigReportVid[] vidsField;

        private byte idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("vid", IsNullable = false)]
        public ToolConfigReportVid[] vids
        {
            get
            {
                return this.vidsField;
            }
            set
            {
                this.vidsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://rudolphtech.com/ToolConfigXMLSchema.xsd")]
    public partial class ToolConfigReportVid
    {

        private string nameField;

        private uint valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public uint Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://rudolphtech.com/ToolConfigXMLSchema.xsd")]
    public partial class ToolConfigReport2
    {

        private ToolConfigReportVid1[] vidsField;

        private ToolConfigReportCeid[] eventsField;

        private byte idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("vid", IsNullable = false)]
        public ToolConfigReportVid1[] vids
        {
            get
            {
                return this.vidsField;
            }
            set
            {
                this.vidsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ceid", IsNullable = false)]
        public ToolConfigReportCeid[] events
        {
            get
            {
                return this.eventsField;
            }
            set
            {
                this.eventsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://rudolphtech.com/ToolConfigXMLSchema.xsd")]
    public partial class ToolConfigReportVid1
    {

        private string nameField;

        private uint valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public uint Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://rudolphtech.com/ToolConfigXMLSchema.xsd")]
    public partial class ToolConfigReportCeid
    {

        private string nameField;

        private uint valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public uint Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
}
